stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/raw_weather_data.csv
    outs:
      - data/processed/processed_weather_data.csv
      - models/scaler.pkl
      - models/label_encoder.pkl
  train:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/processed/processed_weather_data.csv
    outs:
      - models/linear_reg_model.pkl
    metrics:
      - report/metrics.json:
          cache: false
