channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==3.10.0
  - cloudpickle==3.1.2
  - numpy==2.2.6
  - pandas==2.3.3
  - psutil==7.2.2
  - pyarrow==23.0.1
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
